[package]
name = "tokio-iocp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt"] }
windows-sys = { version = "0.36", features = [
    "Win32_Foundation",
    "Win32_Networking_WinSock",
    "Win32_Storage_FileSystem",
    "Win32_System_IO"
] }

[dev-dependencies]
tokio = { version = "1", features = ["net"] }
tempfile = "3.3"
